apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress-1
  namespace: neta-aviv-new
spec:
  ingressClassName: nginx
  rules:
  - host: a794857bc603a4c209ddae88624d6582-171006321.us-east-1.elb.amazonaws.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wordpress-service
            port:
              number: 80
