controller:
  rbac:
    create: "true"
    scope: "true"
  scope:
    enabled: "true"
    namespace: neta-aviv-new
  service:
    type: LoadBalancer
  ingressClassResource:
    name: neta-ingress-class
    enabled: "true"
    default: "true"
    controllerValue: "k8s.io/ingress-nginx"

grafana:
  server:
    root_url: "http://a1bb916ad85bd4e77a3d544445565ebb-839766664.us-east-1.elb.amazonaws.com/grafana"
    serve_from_sub_path: true
