apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-neta
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storage.size }}
  storageClassName: {{ .Values.storageClass.name }}
