apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc-neta
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.wordpress.storage.size }}
  storageClassName:  {{ .Values.storageClass.name }}
